### ISSUE TITLE
Compile error on OSX 10.10 and Xcode 7.2 when Command Line Tools are installed

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/pyobjc#163]
**[Original report](https://bitbucket.org/ronaldoussoren/pyobjc/issue/163) by Ronald Oussoren (Bitbucket: [ronaldoussoren](https://bitbucket.org/ronaldoussoren), GitHub: [ronaldoussoren](https://github.com/ronaldoussoren)).**

----------------------------------------

pyobjc-framework-Cocoa fails to build on OSX 10.10 when the Command Line Tools for Xcode package is installed.

```
#!shell

yosemite:pyobjc-framework-Cocoa-3.1.1 ronald$ python3.5 setup.py build_ext
running build_ext
building 'Foundation._Foundation' extension
/usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -Ibuild/temp.macosx-10.6-intel-3.5/pyobjc-include -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c Modules/_Foundation.m -o build/temp.macosx-10.6-intel-3.5/Modules/_Foundation.o -DPyObjC_BUILD_RELEASE=1010
In file included from Modules/_Foundation.m:15:
Modules/_Foundation_protocols.m:14:28: error: cannot find protocol declaration
      for 'NSProgressReporting'
    p = PyObjC_IdToPython(@protocol(NSProgressReporting)); Py_XDECREF(p);
                           ^
Modules/_Foundation_protocols.m:15:28: error: cannot find protocol declaration
      for 'NSURLSessionStreamDelegate'
    p = PyObjC_IdToPython(@protocol(NSURLSessionStreamDelegate)); Py_XDECREF(p);
                           ^
2 errors generated.
error: command '/usr/bin/clang' failed with exit status 1
```

Reported by Diez B. Roggisch on the pyobjc-dev mailing list.
