### ISSUE TITLE
AttributeError: type object '_WindowAddition' has no attribute 'pyobjc_hiddenSelectors'

### ISSUE THREAD

**Issue by typemytype** [ronaldoussoren/pyobjc#548]
**Describe the bug**

happens with the latest pyobjc 9.1

AttributeError: type object '_WindowAddition' has no attribute 'pyobjc_hiddenSelectors'

**Platform information**

* python 3.9 from python.org

```
 File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_transform.py", line 68, in processClassDict
    new_value = transformAttribute(key, value, class_object, protocols)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/objc/_transform.py", line 484, in transformAttribute
    if selname in cls.pyobjc_hiddenSelectors(isclass):
AttributeError: type object '_WindowAddition' has no attribute 'pyobjc_hiddenSelectors'
```

**Comment by ronaldoussoren** [comment]
Do you have a snippet that reproduces the problem?

**Comment by typemytype** [comment]
yes here it is:

```python
import AppKit
import objc


print(objc.__version__)


class _mixin:
    pass


class NSThing(AppKit.NSObject, _mixin):
    pass


class NSOtherTing(NSThing):

    def __init__(self, **kwargs):
        super()._init__(**kwargs)

    # the open method will cause the error, somehow... 
    def open(self):
        super().open()
```

thanks!!

**Comment by typemytype** [comment]
this worked fine in 9.0.1 but fails with 9.1

**Comment by ronaldoussoren** [comment]
Thanks. Mixin classes are lightly tested, and I didn't have a test with a class with a mixin as a superclass.

**Comment by typemytype** [comment]
thanks for the quick fix!!!

**Comment by ronaldoussoren** [comment]
I've uploaded 9.1.1 with this fix to PyPI.

**Comment by typemytype** [comment]
super!!
