### ISSUE TITLE
pyobjc-compat.h breaks the AvailabiltyMacros.h mechanism

### ISSUE THREAD

**Issue by pepas-everly** [ronaldoussoren/pyobjc#533]
Before `Availability.h` (introduced in 10.5), the older style of OS detection was `AvailabilityMacros.h`.

This header added a new `#define` each time a new version of OS X was released, e.g. `#define MAC_OS_X_VERSION_10_4 1040`.

Though this also defined more complex mechanisms (i.e. `MAC_OS_X_VERSION_MIN_REQUIRED`), the simplest way to guard an include was to simply check for the existence of the corresponding define.

Here's an example of guarding simd.h:

```c
#ifdef __APPLE__
#include <AvailabilityMacros.h>
/* simd.h wasn't available until 10.10. */
#ifdef MAC_OS_X_VERSION_10_10
#include <simd/simd.h>
#endif
#endif
```

Any system older than 10.10 will not have `MAC_OS_X_VERSION_10_10` defined, and every system since 10.10 will have it defined, so this is a reliable mechanism.

Unfortunately, someone has created a fully populated catalog of every such define in `pyobjc-core-9.0.1/Modules/objc/pyobjc-compat.h`:

```
 * Also ensure that MAC_OS_X_VERSION_... macros are available
 * for all existing OSX versions.
 *
 * XXX: Are these really needed?
 */

#ifndef MAC_OS_X_VERSION_10_1
#define MAC_OS_X_VERSION_10_1 1010
#define MAC_OS_X_VERSION_MAX_ALLOWED MAC_OS_X_VERSION_10_1
#endif

#ifndef MAC_OS_X_VERSION_10_2
#define MAC_OS_X_VERSION_10_2 1020
#endif

#ifndef MAC_OS_X_VERSION_10_3
#define MAC_OS_X_VERSION_10_3 1030
#endif
```

This completely breaks how this system is supposed to work.

**Comment by pepas-everly** [comment]
I took a swing at getting pyobjc-core to build on a G5 running 10.5 using gcc (via https://github.com/cellularmitosis/leopard.sh), but ran into the limitations of gcc's obj-c implementation (in particular it doesn't support blocks):

```
Modules/objc/helpers-foundation-nscoder.m: In function 'mkimp_NSCoder_encodeValueOfObjCType_at_':
Modules/objc/helpers-foundation-nscoder.m:84:11: error: expected identifier or '(' before '^' token
     void (^block)(id, const char*, const void*) =
           ^
```

Oh well, maybe someday we'll have working clang on Darwin/PowerPC.

Here's where I left off with this effort for now:

```bash
#!/bin/bash

set -e -o pipefail -x

leopard.sh python-3.11.2
leopard.sh gcc-4.9.4

cd /tmp

if ! test -e pyobjc-core-9.0.1.tar.gz ; then
    export PATH="/opt/tigersh-deps-0.1/bin:$PATH"
    curl --fail -O https://files.pythonhosted.org/packages/1e/20/75b43cd85d8676d15f7d3876e8b64415bfd7b7f937710f9966738723daf3/pyobjc-core-9.0.1.tar.gz
fi

rm -rf pyobjc-core-9.0.1
cat pyobjc-core-9.0.1.tar.gz | gunzip | tar x
cd pyobjc-core-9.0.1

# Leopard's xcrun doesn't understand --show-sdk-path:
patch -p1 << 'EOF'
diff -urN pyobjc-core-9.0.1/PyObjCTest/test_dyld.py pyobjc-core-9.0.1.patched/PyObjCTest/test_dyld.py
--- pyobjc-core-9.0.1/PyObjCTest/test_dyld.py	2022-01-02 05:20:34.000000000 -0600
+++ pyobjc-core-9.0.1.patched/PyObjCTest/test_dyld.py	2023-03-01 17:16:48.000000000 -0600
@@ -254,7 +254,7 @@
             )
 
         else:
-            p = subprocess.check_output(["xcrun", "--show-sdk-path"]).strip()
+            p = "/Developer/SDKs/MacOSX10.5.sdk"
             os.environ["DYLD_LIBRARY_PATH"] = os.path.join(
                 p.decode("utf-8"), "usr", "lib"
             )
diff -urN pyobjc-core-9.0.1/Tools/pyobjc_setup.py pyobjc-core-9.0.1.patched/Tools/pyobjc_setup.py
--- pyobjc-core-9.0.1/Tools/pyobjc_setup.py	2022-06-30 05:21:22.000000000 -0500
+++ pyobjc-core-9.0.1.patched/Tools/pyobjc_setup.py	2023-03-01 17:17:29.000000000 -0600
@@ -470,10 +470,7 @@
     if not sdk:
         # We're likely on a system with the Xcode Command Line Tools.
         # Explicitly use the most recent SDK to avoid compile problems.
-        data = subprocess.check_output(
-            ["/usr/bin/xcrun", "-sdk", "macosx", "--show-sdk-path"],
-            text=True,
-        ).strip()
+        data = "/Developer/SDKs/MacOSX10.5.sdk"
 
         if data:
             sdk_settings_path = os.path.join(data, "SDKSettings.plist")
diff -urN pyobjc-core-9.0.1/setup.py pyobjc-core-9.0.1.patched/setup.py
--- pyobjc-core-9.0.1/setup.py	2022-10-19 02:22:30.000000000 -0500
+++ pyobjc-core-9.0.1.patched/setup.py	2023-03-01 17:15:59.000000000 -0600
@@ -552,10 +552,7 @@
         self.sdk_root = os.environ.get("SDKROOT", None)
         if self.sdk_root is None:
             if os.path.exists("/usr/bin/xcrun"):
-                self.sdk_root = subprocess.check_output(
-                    ["/usr/bin/xcrun", "-sdk", "macosx", "--show-sdk-path"],
-                    text=True,
-                ).strip()
+                self.sdk_root = "/Developer/SDKs/MacOSX10.5.sdk"
 
                 if not self.sdk_root:
                     # With command line tools the value can be empty
EOF

# gcc-4.9: error: unrecognized command line option '-fno-objc-arc'
# gcc-4.9: error: unrecognized command line option '-Wshorten-64-to-32'
# cc1obj: error: unrecognized argument to '-flto=' option: 'thin'
# Modules/objc/method-signature.h:89:5: error: 'for' loop initial declarations are only allowed in C99 or C11 mode
# Modules/objc/OC_PythonArray.m:62:14: error: '-fobjc-exceptions' is required to enable Objective-C exception syntax
patch -p1 << 'EOF'
diff -urN pyobjc-core-9.0.1/setup.py pyobjc-core-9.0.1.patched/setup.py
--- pyobjc-core-9.0.1/setup.py	2022-10-19 02:22:30.000000000 -0500
+++ pyobjc-core-9.0.1.patched/setup.py	2023-03-01 18:14:04.000000000 -0600
@@ -67,10 +67,10 @@
 
 # CFLAGS for the objc._objc extension:
 CFLAGS = [
-    "-g",
+    #"-g",
     "-fexceptions",
     # Explicitly opt-out of ARC
-    "-fno-objc-arc",
+    #"-fno-objc-arc",
     # Loads of warning flags
     "-Wall",
     "-Wstrict-prototypes",
@@ -83,17 +83,19 @@
     "-W",
     "-Wno-import",
     "-Wno-unknown-pragmas",
-    "-Wshorten-64-to-32",
+    #"-Wshorten-64-to-32",
     # "-fsanitize=address", "-fsanitize=undefined", "-fno-sanitize=vptr",
     # "--analyze",
-    "-Werror",
+    #"-Werror",
     "-I/usr/include/ffi",
     "-fvisibility=hidden",
     # "-O0",
-    "-g",
-    "-O3",
-    "-flto=thin",
+    #"-g",
+    #"-O3",
+    #"-flto=thin",
     # XXX: Use object_path_lto (during linking?)
+    "-std=c99",
+    "-fobjc-exceptions",
 ]
 
 # CFLAGS for other (test) extensions:
EOF

# Modules/objc/OC_PythonDictionary.m: In function '-[OC_PythonDictionary removeObjectForKey:]':
# Modules/objc/OC_PythonDictionary.m:310:59: error: stray '@' in program
#                                                   userInfo:@{@"key" : key}];
#                                                             ^
patch -p1 << 'EOF'
diff -urN pyobjc-core-9.0.1/Modules/objc/OC_PythonDictionary.m pyobjc-core-9.0.1.patched/Modules/objc/OC_PythonDictionary.m
--- pyobjc-core-9.0.1/Modules/objc/OC_PythonDictionary.m	2022-02-06 03:24:04.000000000 -0600
+++ pyobjc-core-9.0.1.patched/Modules/objc/OC_PythonDictionary.m	2023-03-01 20:23:41.000000000 -0600
@@ -307,7 +307,7 @@
                     PyObjC_LEAVE_GIL;
                     @throw [NSException exceptionWithName:NSInvalidArgumentException
                                                    reason:@"key does not exist"
-                                                 userInfo:@{@"key" : key}];
+                                                 userInfo:[NSDictionary dictionaryWithObjectsAndKeys:@"key", key, nil]];
                 }
                 PyObjC_GIL_FORWARD_EXC();
             }
@@ -319,7 +319,7 @@
                     PyObjC_LEAVE_GIL;
                     @throw [NSException exceptionWithName:NSInvalidArgumentException
                                                    reason:@"key does not exist"
-                                                 userInfo:@{@"key" : key}];
+                                                 userInfo:[NSDictionary dictionaryWithObjectsAndKeys:@"key", key, nil]];
                 }
                 PyObjC_GIL_FORWARD_EXC();
             }
EOF

patch -p1 << 'EOF'
diff -urN pyobjc-core-9.0.1/Modules/objc/ctests.m pyobjc-core-9.0.1.patched/Modules/objc/ctests.m
--- pyobjc-core-9.0.1/Modules/objc/ctests.m	2022-10-18 04:53:23.000000000 -0500
+++ pyobjc-core-9.0.1.patched/Modules/objc/ctests.m	2023-03-01 21:22:29.000000000 -0600
@@ -8,7 +8,14 @@
 #include "pyobjc-unittest.h"
 
 #include <fcntl.h>
+
+#ifdef __APPLE__
+#include <AvailabilityMacros.h>
+/* simd.h was introduced in 10.10. */
+#ifdef MAC_OS_X_VERSION_10_10
 #include <simd/simd.h>
+#endif
+#endif
 
 // LCOV_BR_EXCL_START
 // LCOV_EXCL_START
@@ -100,6 +107,7 @@
  *      that are wrapped in PyObjC.
  */
 BEGIN_UNITTEST(VectorSize)
+#ifdef __SIMD_HEADER__
 ASSERT_EQUALS(sizeof(vector_uchar16), PyObjCRT_SizeOfType("<16C>"), "%d");
 ASSERT_EQUALS(sizeof(vector_short2), PyObjCRT_SizeOfType("<2s>"), "%d");
 ASSERT_EQUALS(sizeof(vector_ushort2), PyObjCRT_SizeOfType("<2S>"), "%d");
@@ -112,6 +120,7 @@
 ASSERT_EQUALS(sizeof(vector_double2), PyObjCRT_SizeOfType("<2d>"), "%d");
 ASSERT_EQUALS(sizeof(vector_double3), PyObjCRT_SizeOfType("<3d>"), "%d");
 ASSERT_EQUALS(sizeof(vector_double4), PyObjCRT_SizeOfType("<4d>"), "%d");
+#endif
 
 Py_ssize_t n = PyObjCRT_SizeOfType("<4,4di");
 FAIL_IF(n != -1);
@@ -124,6 +133,7 @@
 END_UNITTEST
 
 BEGIN_UNITTEST(VectorAlign)
+#ifdef __SIMD_HEADER__
 ASSERT_EQUALS(__alignof__(vector_uchar16), PyObjCRT_AlignOfType("<16C>"), "%d");
 ASSERT_EQUALS(__alignof__(vector_short2), PyObjCRT_AlignOfType("<2s>"), "%d");
 ASSERT_EQUALS(__alignof__(vector_ushort2), PyObjCRT_AlignOfType("<2S>"), "%d");
@@ -136,6 +146,7 @@
 ASSERT_EQUALS(__alignof__(vector_double2), PyObjCRT_AlignOfType("<2d>"), "%d");
 ASSERT_EQUALS(__alignof__(vector_double3), PyObjCRT_AlignOfType("<3d>"), "%d");
 ASSERT_EQUALS(__alignof__(vector_double4), PyObjCRT_AlignOfType("<4d>"), "%d");
+#endif
 
 Py_ssize_t n = PyObjCRT_AlignOfType("<4,4di");
 FAIL_IF(n != -1);
EOF

patch -p1 << 'EOF'
diff -urN pyobjc-core-9.0.1/Modules/objc/pyobjc-compat.h pyobjc-core-9.0.1.patched/Modules/objc/pyobjc-compat.h
--- pyobjc-core-9.0.1/Modules/objc/pyobjc-compat.h	2022-12-17 04:07:28.000000000 -0600
+++ pyobjc-core-9.0.1.patched/Modules/objc/pyobjc-compat.h	2023-03-01 21:09:14.000000000 -0600
@@ -39,267 +39,6 @@
 
 /*
  *
- * Start of Cocoa definitions
- *
- *
- * Ensure that CGFloat and NSInteger are always
- * available, even when compiling with ancient SDKs.
- *
- * Also ensure that MAC_OS_X_VERSION_... macros are available
- * for all existing OSX versions.
- *
- * XXX: Are these really needed?
- */
-
-#ifndef MAC_OS_X_VERSION_10_1
-#define MAC_OS_X_VERSION_10_1 1010
-#define MAC_OS_X_VERSION_MAX_ALLOWED MAC_OS_X_VERSION_10_1
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_2
-#define MAC_OS_X_VERSION_10_2 1020
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_3
-#define MAC_OS_X_VERSION_10_3 1030
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_4
-#define MAC_OS_X_VERSION_10_4 1040
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_5
-#define MAC_OS_X_VERSION_10_5 1050
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_6
-#define MAC_OS_X_VERSION_10_6 1060
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_7
-#define MAC_OS_X_VERSION_10_7 1070
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_8
-#define MAC_OS_X_VERSION_10_8 1080
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_9
-#define MAC_OS_X_VERSION_10_9 1090
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_10
-#define MAC_OS_X_VERSION_10_10 101000
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_10_2
-#define MAC_OS_X_VERSION_10_10_2 101002
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_10_3
-#define MAC_OS_X_VERSION_10_10_3 101003
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_11
-#define MAC_OS_X_VERSION_10_11 101100
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_11_1
-#define MAC_OS_X_VERSION_10_11_1 101101
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_11_2
-#define MAC_OS_X_VERSION_10_11_2 101102
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_11_3
-#define MAC_OS_X_VERSION_10_11_3 101103
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_11_4
-#define MAC_OS_X_VERSION_10_11_4 101104
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_12
-#define MAC_OS_X_VERSION_10_12 101200
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_12_1
-#define MAC_OS_X_VERSION_10_12_1 101201
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_12_2
-#define MAC_OS_X_VERSION_10_12_2 101202
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_12_4
-#define MAC_OS_X_VERSION_10_12_4 101204
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_13
-#define MAC_OS_X_VERSION_10_13 101300
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_13_1
-#define MAC_OS_X_VERSION_10_13_1 101301
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_13_2
-#define MAC_OS_X_VERSION_10_13_2 101302
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_13_3
-#define MAC_OS_X_VERSION_10_13_3 101303
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_13_4
-#define MAC_OS_X_VERSION_10_13_4 101304
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_13_5
-#define MAC_OS_X_VERSION_10_13_5 101305
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_13_6
-#define MAC_OS_X_VERSION_10_13_6 101306
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_14
-#define MAC_OS_X_VERSION_10_14 101400
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_14_1
-#define MAC_OS_X_VERSION_10_14_1 101401
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_14_2
-#define MAC_OS_X_VERSION_10_14_2 101402
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_14_3
-#define MAC_OS_X_VERSION_10_14_3 101403
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_14_4
-#define MAC_OS_X_VERSION_10_14_4 101404
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_14_5
-#define MAC_OS_X_VERSION_10_14_5 101405
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_14_6
-#define MAC_OS_X_VERSION_10_14_6 101406
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_15
-#define MAC_OS_X_VERSION_10_15 101500
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_15_1
-#define MAC_OS_X_VERSION_10_15_1 101501
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_15_2
-#define MAC_OS_X_VERSION_10_15_2 101502
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_15_3
-#define MAC_OS_X_VERSION_10_15_3 101503
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_15_4
-#define MAC_OS_X_VERSION_10_15_4 101504
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_15_5
-#define MAC_OS_X_VERSION_10_15_5 101505
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_15_6
-#define MAC_OS_X_VERSION_10_15_6 101506
-#endif
-
-#ifndef MAC_OS_X_VERSION_10_16
-#define MAC_OS_X_VERSION_10_16 101600
-#endif
-
-#ifndef MAC_OS_X_VERSION_11_0
-#define MAC_OS_X_VERSION_11_0 110000
-#endif
-
-#ifndef MAC_OS_X_VERSION_11_1
-#define MAC_OS_X_VERSION_11_1 110100
-#endif
-
-#ifndef MAC_OS_X_VERSION_11_2
-#define MAC_OS_X_VERSION_11_2 110200
-#endif
-
-#ifndef MAC_OS_X_VERSION_11_3
-#define MAC_OS_X_VERSION_11_3 110300
-#endif
-
-#ifndef MAC_OS_X_VERSION_11_4
-#define MAC_OS_X_VERSION_11_4 110400
-#endif
-
-#ifndef MAC_OS_X_VERSION_11_5
-#define MAC_OS_X_VERSION_11_5 110500
-#endif
-
-#ifndef MAC_OS_X_VERSION_11_6
-#define MAC_OS_X_VERSION_11_6 110600
-#endif
-
-#ifndef MAC_OS_X_VERSION_12_0
-#define MAC_OS_X_VERSION_12_0 120000
-#endif
-
-#ifndef MAC_OS_X_VERSION_12_1
-#define MAC_OS_X_VERSION_12_1 120100
-#endif
-
-#ifndef MAC_OS_X_VERSION_12_2
-#define MAC_OS_X_VERSION_12_2 120200
-#endif
-
-#ifndef MAC_OS_X_VERSION_12_3
-#define MAC_OS_X_VERSION_12_3 120300
-#endif
-
-#ifndef MAC_OS_X_VERSION_12_4
-#define MAC_OS_X_VERSION_12_4 120400
-#endif
-
-#ifndef MAC_OS_X_VERSION_12_5
-#define MAC_OS_X_VERSION_12_5 120500
-#endif
-
-#ifndef MAC_OS_X_VERSION_12_6
-#define MAC_OS_X_VERSION_12_6 120600
-#endif
-
-#ifndef MAC_OS_X_VERSION_13_0
-#define MAC_OS_X_VERSION_13_0 130000
-#endif
-
-#ifndef MAC_OS_X_VERSION_13_1
-#define MAC_OS_X_VERSION_13_1 130100
-#endif
-
-#ifndef MAC_OS_X_VERSION_13_2
-#define MAC_OS_X_VERSION_13_2 130200
-#endif
-
-/*
- *
- * End of Cocoa definitions
- *
- */
-
-/*
- *
  * Start of compiler support helpers
  *
  * XXX: Are these needed?
EOF

env CC="gcc-4.9 -m64" python3 setup.py build
env CC="gcc-4.9 -m64" python3 setup.py install --prefix=/opt/python-3.11.2

```

**Comment by ronaldoussoren** [comment]
I'm not sure I understand the problem. Why does defining these macro's in PyObjC break things? PyObjC's code does not use the ``#ifdef ...`` pattern you mention.

Also, current versions of PyObjC do not support macOS 10.5 or PPC and never will. The project currently only supports macOS 10.9 or later for x86_64 and arm64.    Older versions of PyObjC did support PPC and OSX 10.5 though, although I don't know from the top of my head which versions, the latest 5.x release would be my first guess.

**Comment by pepas-everly** [comment]
> the latest 5.x release would be my first guess.

Ah thanks for the pointer!

> Why does defining these macro's in PyObjC break things?

As an example, some of the pyobjc unit tests try to import `simd.h`, which didn't exist until OS X 10.10.

This simple guard should take care of that:

```
#ifdef __APPLE__
#include <AvailabilityMacros.h>
/* simd.h wasn't available until 10.10. */
#ifdef MAC_OS_X_VERSION_10_10
#include <simd/simd.h>
#endif
#endif
```

On systems which are 10.10 and newer, `MAC_OS_X_VERSION_10_10` will exist in `AvailabilityMacros.h`, and so `simd.h` will get included.

On systems which are older than 10.10, `MAC_OS_X_VERSION_10_10` doesn't exist, so `simd.h` is _not_ included.

However, because the pyobjc header goes out of its way to define `MAC_OS_X_VERSION_10_10`, that breaks the `#ifdef` logic for every system prior to 10.10 and they all try to include `simd.h`.

Does that make sense?  There is no reason to define extra `MAC_OS_X_VERSION_X_Y` which shouldn't exist on older systems.

**Comment by ronaldoussoren** [comment]
> This simple guard should take care of that:
> 
> ```c
> #ifdef __APPLE__
> #include <AvailabilityMacros.h>
> /* simd.h wasn't available until 10.10. */
> #ifdef MAC_OS_X_VERSION_10_10
> #include <simd/simd.h>
> #endif
> #endif
> ```

I generally use guards with ``PyObjC_BUILD_RELEASE`` for this. PyObjC's setup.py defines that macro with the major/minor version of the SDK used. 

```c
> #ifdef __APPLE__
> #include <AvailabilityMacros.h>
> /* simd.h wasn't available until 10.10. */
> #if PyObjC_BUILD_RELEASE >= 1010
> #include <simd/simd.h>
> #endif
> #endif
```

**Comment by ronaldoussoren** [comment]
> > the latest 5.x release would be my first guess.
> 
> Ah thanks for the pointer!

Note that the 5.x version does not support recent versions of Python, in particular some changes to deal with changes in the bytecode format. Those changes should be easy enough to port back to older versions of PyObjC though.

Forward porting support for PPC and in particular 32-bit is likely harder, removing support for 32-bit code allowed for some simplification in pyobjc-core (both because of low-level differences between PPC and other architectures and more importantly because 32-bit uses a different objective-c runtime).
