### ISSUE TITLE
Quartz interface fails to build on MacOS 15

### ISSUE THREAD

**Issue by ngoldbaum** [ronaldoussoren/pyobjc#671]
**Describe the bug**

All pyobjc dependencies build on Python 3.15 except for `pyobjc-framework-Quartz`:

```
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk -I/Users/goldbaum/.pyenv/versions/3.15t-dev/include/python3.15t -c Modules/_coregraphics.m -o build/temp.macosx-15.7-arm64-cpython-315t/Modules/_coregraphics.o -Wno-deprecated-declarations -DPyObjC_BUILD_RELEASE=2602 -Werror -DPyObjC_GIL_DISABLED
      Modules/_coregraphics.m:243:17: error: 'CGWindowListCreateImageFromArray' is unavailable: obsoleted in macOS 15.0 - Please use ScreenCaptureKit instead.
        243 |                 CGWindowListCreateImageFromArray(screenBounds, windowArray, imageOption);
            |                 ^
      /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX26.2.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGWindow.h:280:33: note: 'CGWindowListCreateImageFromArray' has been explicitly marked unavailable here
        280 | CG_EXTERN CGImageRef __nullable CGWindowListCreateImageFromArray(
            |                                 ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
```

**Platform information**

* Python version `Python 3.15.0a7+ free-threading build (heads/main:74a82a2, Apr  2 2026, 14:08:21) [Clang 17.0.0 (clang-1700.6.4.2)]`
* How was python installed (python.org, anaconda, homebrew, ...) `pyenv install 3.15t-dev`
* macOS version Sequoia 15.7.5 (24G624)

**To Reproduce**

`pip install pyobjc-framework-Quartz`

**Expected behavior**
The build should succeed.

**Additional context**
I'm trying to run the setuptools tests on Python 3.15 and PyObjc is a mac-specific indirect test dependency of setuptools.

**Comment by ronaldoussoren** [comment]
The issue is not specific to Python 3.15,  you'll get the same error when installing this framework on an older version of Python when forcing a build from source.

I try to keep compatibility with older version of the macOS SDK, but it looks like this is broken for this extension. Annoyingly I cannot reproduce at the moment, although I haven't build on macOS 15 for a while now. The SDK mentioned is recent enough that I didn't expect problems.

One thing you could to do to work around the issue: ``export MACOSX_DEPLOYMENT_TARGET=15.1`` before building the extension. That should skip the problematic function.

**Comment by ronaldoussoren** [comment]
Could you try this patch?  It probably won't work, but it is worth trying.

```diff
diff --git a/pyobjc-framework-Quartz/Modules/_coregraphics.m b/pyobjc-framework-Quartz/Modules/_coregraphics.m
index 0af9ce939..d81da8b3e 100644
--- a/pyobjc-framework-Quartz/Modules/_coregraphics.m
+++ b/pyobjc-framework-Quartz/Modules/_coregraphics.m
@@ -239,6 +239,8 @@
         @try {
 #pragma clang diagnostic push
 #pragma clang diagnostic ignored "-Wdeprecated-declarations"
+#pragma clang diagnostic ignored "-Wunguarded-availability-new"
+#pragma clang diagnostic ignored "-Wunguarded-availability"
             image =
                 CGWindowListCreateImageFromArray(screenBounds, windowArray, imageOption);
 #pragma clang diagnostic pop
```

**Comment by ngoldbaum** [comment]
Unfortunately neither your patch or setting `MACOSX_DEPLOYMENT_TARGET=15.1` fixes the build issue on my machine. I tried both alone and in combination.

**Comment by ronaldoussoren** [comment]
I finally got around to spinning up a macOS 15 VM, but cannot reproduce the issue at the moment: the Quartz bindings build fine, but the Metal bindings don't.  This is with the tip of the pyobjc tree and Xcode 16.4 (16F6).

What's the version of Apple's compiler on your system?

``xcodebuild -version`` definitely shows this when you have Xcode installed, I'm not 100% sure if that also works when only the command line tools are installed.  ``xcrun --sdk macosx --show-sdk-version`` would also be useful if ``xcodebuild`` fails.

PS. I'm working on a release for PyObjC and that will include binary wheels for Python 3.15.

**Comment by ronaldoussoren** [comment]
~(currently upgrading the macOS 15 VM to 15.7 in preparation for testing with Xcode 26.3 (the latest Xcode release that supports running on Xcode 15)~

The tip of the tree builds fine on macOS 15.7.7 (24G720) with Xcode 26.3 (17C529).

``pip install --no-binary :all: pyobjc-framework-Quartz`` on the same system (and using Python 3.15b1) downloads sdists for ``pyobjc-framework-Quartz``, ``pyobjc-framework-Cocoa`` and ``pyobjc-core`` and builds binary wheels for them before installing.   This didn't work with Xcode 16.4 because ``pyobjc-core`` fails to build with that compiler (fixed in the tip of the tree).

**Comment by ngoldbaum** [comment]
Well I guess as soon as you upload wheels for the pyobjc stack this issue will go away for me.

FWIW on MacOS 26.4.1 (25E253) and the newest version of the command-line tools (26.4.1.0.1775747724) I still see the same build error on the `main` branch.

**Comment by ronaldoussoren** [comment]
I've uploaded wheels for 12.2, including ones supporting Python 3.15.

**Comment by ronaldoussoren** [comment]
> Well I guess as soon as you upload wheels for the pyobjc stack this issue will go away for me.
> 
> FWIW on MacOS 26.4.1 (25E253) and the newest version of the command-line tools (26.4.1.0.1775747724) I still see the same build error on the `main` branch.

I wonder what the difference is between our build environments. The only difference I see so far is the OS release (I'm on macOS 26.5 [25F71]).  The Quartz bindings build both with the command-line tools (latest version installed according to the software update tool) and Xcode (26.5).     I haven't tried building with the command-line tools on an Intel system, but builds using Xcode work both on arm64 and x86_64.

I guess there's another difference: given your initial report you're using pyenv to install python and I'm using the python.org macOS installer. That shouldn't be relevant for the error you're seeing though.

**Comment by ronaldoussoren** [comment]
> I guess there's another difference: given your initial report you're using pyenv to install python and I'm using the python.org macOS installer. That shouldn't be relevant for the error you're seeing though.

Except that it is. I can now reproduce the issue locally using ``MACOSX_DEPLOYMENT_TARGET=26.0 python setup.py build_ext`` (the default deployment target for the Python.org installer is a lot older than that).

**Comment by ronaldoussoren** [comment]
The code tried to guard against this change, but the version test macro used for this doesn't exist (older macOS version macro's are fine).
